targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
      retrofit:
        options:
          type: retrofit
          generated_file_name: "api_service.g.dart"
          generate_headers: true
          generate_to_json: true
          generate_dio_handlers: true
          use_result_type: true
          include_if_null: false
